GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/618d9a4d2a4605cd5972c2fd

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Paweł Elo",
    "number": "435 735 213"
}

###

DELETE  http://localhost:3001/api/persons/618d970ee4dca774e1e86a35
