GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/618d47f09f611e732c67d8ed

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "marik",
    "number": "1234"
}

###

PUT http://localhost:3001/api/persons/618e34f0c2aa80b87dd8add0
content-type: application/json

{
    "name": "marik",
    "number": "12345"
}

###

DELETE  http://localhost:3001/api/persons/618e30047f3448a21a18db07
