GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/618d47f09f611e732c67d8ed

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "marik1234",
    "number": "12345678"
}

###

PUT http://localhost:3001/api/persons/618eb82ba03f60bd709b8ae8
content-type: application/json

{
    "name": "marik",
    "number": "123456"
}

###

DELETE  http://localhost:3001/api/persons/618eb704a03f60bd709b8ac6
